name: Deploy Workflow
run-name: ${{github.actor}} is deploying the project
on:
  push:
    branches:
      - user-controller-changes
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd km-service

      - name: Install dependencies
        run: npm install
        working-directory: km-service

      - name: Install Vite globally
        run: npm install -g vite
        working-directory: km-service

      - name: Build
        run: npm run build
        working-directory: km-service

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/html/<your_project_directory>/
          remote_host: 172.31.3.109
          remote_user: ec2-user
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
