name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set key
      id: setup-key
      env:
        DEPLOY_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/Key.pem
        chmod 400 ~/.ssh/Key.pem
        
    - name: Connect SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/Key.pem ec2-user@ec2-3-111-41-198.ap-south-1.compute.amazonaws.com "cd /home/ec2-user/git_action/practice && git pull origin main"
