name: Deploy to EC2

on:
  push:
    branches:
      - main
run-name: ${{github.actor}} is building the project

jobs:
  Build-Maven-Project:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      
      - name: Build with Maven
        run: |
          cd km-service
          mvn clean install
   #  - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/*.jar

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Package
          path: target/

      - name: Set key
        id: setup-key
        env:
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/Key.pem
          chmod 400 ~/.ssh/Key.pem
    
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ec2-user/git_action/practice"
        
      - name: Connect SSH
        run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/Key.pem ec2-user@ec2-3-111-41-198.ap-south-1.compute.amazonaws.com "cd /home/ec2-user/git_action/practice && git pull origin main"
